kind: pipeline
name: default

workspace:
  path: /drone/src

steps:
- name: run-existing
  pull: always
  image: dnyaneshwarnagre/blazemeter:drone
  environment:   
    apikey: ''
    apisecret: ''
    testid: ''
    showtaillog: false
    #modeldata: '{"email": "\"asd@gmail.com\"", "password": "\"123456\""}'
    #modeldata: '{"url": "\"https://blazedemo.com/\""}'
    
##### Update yml file
    #uploadfilechk: true
    #inputallfiles: dependencies #BlazeDemo.yaml
    #env_variable: '{"username":"\"dn654\"","password":"\"abczyt\""}'
    
##### Create new test 
    #createtest: true
    #testname: "drone-test5"
    #projectid: 961236
    #inputstartfile: BlazeDemo.yaml
    #inputstartfile: /drone/src/dependencies/SampleAPIStrong.yaml
    
##### Download artifact set to false
    continuepipeline: false
    
##### Jmeter Properties
    #jmeterproperties: "test=dronetest1,test=dronetest12,test=dronetest1223"
    
##### report name
    reportname: "dronetest1"
    
##### note
    note: "dronetest1"

##### Testing step for artifacts download
- name: display dirs
  image: alpine
  commands:
    - ls
    - pwd
    - ls ./tmp/artifacts
